<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

// 📚 LEARNING: A Migration is a version-controlled change to your database schema.
// Instead of writing raw SQL and running it manually, you write PHP code here.
// Laravel runs these in order, so your schema is always reproducible on any machine.
// `php artisan migrate`        → runs pending migrations
// `php artisan migrate:rollback` → undoes the last batch of migrations

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * A "conversation" groups related messages together under one chat session.
     * For Phase 2 we use Laravel's session_id as the owner identifier
     * (no auth/login system yet — that's Phase 3+).
     */
    public function up(): void
    {
        Schema::create('conversations', function (Blueprint $table) {
            // 📚 LEARNING: id() creates an auto-incrementing BIGINT primary key named "id".
            // This is the standard Laravel convention.
            $table->id();

            // 📚 LEARNING: We store the Laravel session ID so we can tie
            // this conversation to the correct browser session.
            // session_id() is a string like "abc123XYZ..." generated by Laravel.
            // index() creates a database index so lookups by session_id are fast.
            $table->string('session_id')->index();

            // Optional title for the conversation (could be auto-generated from first message later).
            $table->string('title')->nullable();

            // 📚 LEARNING: timestamps() adds two columns automatically:
            //   created_at → when the row was inserted
            //   updated_at → when the row was last changed
            // Laravel's Eloquent ORM manages these automatically — you never set them manually.
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * 📚 LEARNING: down() is called when you run `php artisan migrate:rollback`.
     * It should UNDO exactly what up() did. dropIfExists() drops the table if it exists,
     * silently doing nothing if it doesn't (safe to call multiple times).
     */
    public function down(): void
    {
        Schema::dropIfExists('conversations');
    }
};
